package com.cmc.global.asset.gateway.dto;

import java.util.List;

/**
 * Auto generated by jpa-maven-plugin
 * 
 * @author vhtu1
 * @date 2021-01-20 03:09:28
 */
public class Users {
    private List<UsersDto> items;

    public List<UsersDto> getItems() {
        return items;
    }

    public void setItems(List<UsersDto> items) {
        this.items = items;
    }

}