package com.cmc.global.assetservice.model;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Auto generated by jpa-maven-plugin
 * 
 * @author vhtu1
 * @date 2021-01-20 03:09:28
 */
@Data
@Entity
@Table(name = "assets")
@EqualsAndHashCode(callSuper = false)
public class Assets {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "type_id")
    private AssetType type;

    @Column(name = "asset_code", length = 30)
    @NotEmpty
    private String assetCode;

    @Column(name = "asset_name", length = 100)
    @NotEmpty
    private String assetName;

    @Column(name = "description", length = 100)
    @NotEmpty
    private String description;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private Users user;

    @ManyToOne
    @JoinColumn(name = "dept_id")
    private Departments department;

}