package com.cmc.global.assetservice.model;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Auto generated by jpa-maven-plugin
 * 
 * @author vhtu1
 * @date 2021-01-20 03:09:28
 */
@Data
@Entity
@Table(name = "users")
public class Users {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "name", length = 100)
    @NotEmpty
    private String name;

    @Column(name = "email", length = 50)
    @NotEmpty
    private String email;

    @Column(name = "password", length = 30)
    @NotEmpty
    private String password;

    @Column(name = "description", length = 100)
    @NotEmpty
    private String description;

}