package com.cmc.global.usersservice.model;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Auto generated by jpa-maven-plugin
 * 
 * @author vhtu1
 * @date 2021-01-20 03:09:28
 */
@Data
@Entity
@Table(name = "departments")
@EqualsAndHashCode(callSuper = false)
public class Departments {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "department_name")
    @NotEmpty
    private String departmentName;

    @Column(name = "description")
    @NotEmpty
    private String description;

}